version: "2"

# Find the whole list here https://golangci-lint.run/usage/linters/
linters:
  default: none
  enable:
    - asciicheck # simple linter to check that your code does not contain non-ASCII identifiers
    - bodyclose # checks whether HTTP response body is closed successfully
    - depguard # checks if package imports are in a list of acceptable packages
    - durationcheck # check for two durations multiplied together
    - errcheck # checking for unchecked errors in go programs
    - errorlint # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - forbidigo # forbids identifiers	matched by reg exps
    - gomoddirectives # manage the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard # check for blocked dependencies
    - gosec # inspects source code for security problems
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - importas # enforces consistent import aliases
    - ineffassign # detects when assignments to existing variables are not used
    - misspell # finds commonly misspelled English words in comments
    - nakedret # finds naked returns in functions greater than a specified function length
    - nilerr # finds the code that returns nil even if it checks that the error is not nil
    - noctx # noctx finds sending http request without context.Context
    - nolintlint # reports ill-formed or insufficient nolint directives
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unconvert # Remove unnecessary type conversions
    - unused # checks Go code for unused constants, variables, functions and types
    - wastedassign # wastedassign finds wasted assignment statements

  # all available settings of specific linters
  settings:
    depguard:
      rules:
        main:
          # Defines package matching behavior.
          list-mode: lax # allowed if it doesn't match the deny list or the allow rule is more specific (longer) than the deny rule
          # List of packages that are not allowed.
          deny:
            - pkg: math/rand$
              desc: superseded by math/rand/v2

    errcheck:
      # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
      check-type-assertions: true
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      check-blank: false
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - (mapstr.M).Delete
        - (mapstr.M).Put

    errorlint:
      # Check whether fmt.Errorf uses the %w verb for formatting errors. See the readme for caveats
      errorf: true
      # Check for plain type assertions and type switches
      asserts: true
      # Check for plain error comparisons
      comparison: true

    forbidigo:
      # Forbid the following identifiers
      forbid:
        - pattern: fmt.Print.* # too much log noise
      # Exclude godoc examples from forbidigo checks. Default is true.
      exclude-godoc-examples: true

    gomoddirectives:
      # Allow local `replace` directives. Default is false.
      replace-local: false

    gomodguard:
      # List of blocked modules.
      blocked:
        modules:
          # Blocked module.
          - github.com/pkg/errors:
              # Recommended modules that should be used instead. (Optional)
              recommendations:
                - errors
                - fmt
              reason: This package is deprecated, use fmt.Errorf with %%w instead
          - github.com/elastic/beats/v7:
              reason: There must be no Beats dependency
    gosec:
      excludes:
        - G306 # Expect WriteFile permissions to be 0600 or less
        - G404 # Use of weak random number generator
        - G401 # Detect the usage of DES, RC4, MD5 or SHA1: Used in non-crypto contexts.
        - G501 # Import blocklist: crypto/md5: Used in non-crypto contexts.
        - G505 # Import blocklist: crypto/sha1: Used in non-crypto contexts.

    nolintlint:
      # Enable to require an explanation of nonzero length after each nolint directive. Default is false.
      require-explanation: true
      # Enable to require nolint directives to mention the specific linter being suppressed. Default is false.
      require-specific: true
      # Enable to ensure that nolint directives are all used. Default is true.
      allow-unused: false
      # Exclude following linters from requiring an explanation.  Default is [].
      allow-no-explanation: [ ]

    staticcheck:
      checks:
        - all

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - forbidigo
        path: (.*magefile.go|.*dev-tools/mage/.*)
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
